export const ADD_APPOINTMENT = "ADD_APPOINTMENT"
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT"
export const ADD_DESCRIPTION = "ADD_DESCRIPTION"
export const ADD_APPOINTMENTS = "ADD_APPOINTMENTS"
export const APPOINTMENTS_FAILED = "APPOINTMENTS_FAILED"
export const ADD_DOCTORS = "ADD_DOCTORS"
export const DOCTORS_FAILED = "DOCTORS_FAILED"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_AVAILABILITY = "ADD_AVAILABILITY"
export const DELETE_AVAILABILITY = "DELETE_AVAILABILITY"

