export const ADD_APPOINTMENT = "ADD_APPOINTMENT"
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT"
export const ADD_DESCRIPTION = "ADD_DESCRIPTION"
export const ADD_APPOINTMENTS = "ADD_APPOINTMENTS"
export const APPOINTMENTS_FAILED = "APPOINTMENTS_FAILED"
export const ADD_DOCTORS = "ADD_DOCTORS"
export const DOCTORS_FAILED = "DOCTORS_FAILED"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_AVAILABILITY = "ADD_AVAILABILITY"
export const DELETE_AVAILABILITY = "DELETE_AVAILABILITY"

export const ADD_PATIENTS = "ADD_PATIENTS"
export const PATIENTS_FAILED = "PATIENTS_FAILED"

export const ADD_TIMESLOTS = "ADD_TIMESLOTS"
export const TIMESLOTS_FAILED = "TIMESLOTS_FAILED"

export const ADD_SPECIALITIES = "ADD_SPECIALITIES"
export const SPECIALITIES_FAILED = "SPECIALITIES_FAILED"

export const ADD_PROFESSIONS = "ADD_PROFESSIONS"
export const PROFESSIONS_FAILED = "PROFESSIONS_FAILED"
