export const ADD_APPOINTMENT = "ADD_APPOINTMENT"
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT"
export const ADD_DESCRIPTION = "ADD_DESCRIPTION"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";